// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q       = new(Query)
	Class   *class
	College *college
	Major   *major
	School  *school
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Class = &Q.Class
	College = &Q.College
	Major = &Q.Major
	School = &Q.School
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:      db,
		Class:   newClass(db, opts...),
		College: newCollege(db, opts...),
		Major:   newMajor(db, opts...),
		School:  newSchool(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Class   class
	College college
	Major   major
	School  school
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:      db,
		Class:   q.Class.clone(db),
		College: q.College.clone(db),
		Major:   q.Major.clone(db),
		School:  q.School.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:      db,
		Class:   q.Class.replaceDB(db),
		College: q.College.replaceDB(db),
		Major:   q.Major.replaceDB(db),
		School:  q.School.replaceDB(db),
	}
}

type queryCtx struct {
	Class   IClassDo
	College ICollegeDo
	Major   IMajorDo
	School  ISchoolDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Class:   q.Class.WithContext(ctx),
		College: q.College.WithContext(ctx),
		Major:   q.Major.WithContext(ctx),
		School:  q.School.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	return &QueryTx{q.clone(q.db.Begin(opts...))}
}

type QueryTx struct{ *Query }

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
