// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameCollege = "college"

// College mapped from table <college>
type College struct {
	ID       int64                 `gorm:"column:id;type:int(11);primaryKey" json:"id"`                         // id
	Name     string                `gorm:"column:name;type:varchar(32);not null" json:"name"`                   // 学院名称
	IsDelete soft_delete.DeletedAt `gorm:"column:is_delete;type:int unsigned;softDelete:flag" json:"is_delete"` // 是否有效
}

// TableName College's table name
func (*College) TableName() string {
	return TableNameCollege
}
