// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLog = "log"

// Log mapped from table <log>
type Log struct {
	ID         int64     `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`  // id
	State      int8      `gorm:"column:state;type:tinyint(4);not null" json:"state"`              // 日志状态
	Method     int8      `gorm:"column:method;type:tinyint(4);not null" json:"method"`            // 操作方法
	Content    string    `gorm:"column:content;type:varchar(128);not null" json:"content"`        // 内容
	OperatorID int64     `gorm:"column:operator_id;type:int(11);not null" json:"operator_id"`     // 操作者id
	OperatorIP string    `gorm:"column:operator_ip;type:varchar(16);not null" json:"operator_ip"` // 操作者ip
	CreatedAt  time.Time `gorm:"column:created_at;type:datetime;not null" json:"created_at"`      // 生成时间
}

// TableName Log's table name
func (*Log) TableName() string {
	return TableNameLog
}
