// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameMajor = "major"

// Major mapped from table <major>
type Major struct {
	ID        int64                 `gorm:"column:id;type:int(11);primaryKey" json:"id"`                         // id
	Name      string                `gorm:"column:name;type:varchar(32);not null" json:"name"`                   // 专业名称
	CollegeID int64                 `gorm:"column:college_id;type:int(11);not null" json:"college_id"`           // 学院
	IsDelete  soft_delete.DeletedAt `gorm:"column:is_delete;type:int unsigned;softDelete:flag" json:"is_delete"` // 是否有效
}

// TableName Major's table name
func (*Major) TableName() string {
	return TableNameMajor
}
