// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameNotice = "notice"

// Notice mapped from table <notice>
type Notice struct {
	ID        int64                 `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`      // id
	Headline  string                `gorm:"column:headline;type:varchar(128);not null" json:"headline"`          // 标题
	Content   string                `gorm:"column:content;type:text;not null" json:"content"`                    // 内容
	FileID    int64                 `gorm:"column:file_id;type:int(11);not null" json:"file_id"`                 // 文件id
	CollegeID int64                 `gorm:"column:college_id;type:int(11);not null" json:"college_id"`           // 学院id
	MajorID   int64                 `gorm:"column:major_id;type:int(11);not null" json:"major_id"`               // 专业id
	Company   string                `gorm:"column:company;type:varchar(16);not null" json:"company"`             // 发布单位
	CreatedAt time.Time             `gorm:"column:created_at;type:datetime;not null" json:"created_at"`          // 发布时间
	IsDelete  soft_delete.DeletedAt `gorm:"column:is_delete;type:int unsigned;softDelete:flag" json:"is_delete"` // 存在标志
}

// TableName Notice's table name
func (*Notice) TableName() string {
	return TableNameNotice
}
