// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNamePlan = "plan"

// Plan mapped from table <plan>
type Plan struct {
	ID        int64                 `gorm:"column:id;type:int(11);primaryKey" json:"id"`                         // id
	Content   string                `gorm:"column:content;type:varchar(128);not null" json:"content"`            // 计划内容
	Week      int8                  `gorm:"column:week;type:tinyint(4);not null" json:"week"`                    // 计划时间（周）
	SubjectID int64                 `gorm:"column:subject_id;type:int(11);not null" json:"subject_id"`           // 题目Id
	IsDelete  soft_delete.DeletedAt `gorm:"column:is_delete;type:int unsigned;softDelete:flag" json:"is_delete"` // 存在标志
}

// TableName Plan's table name
func (*Plan) TableName() string {
	return TableNamePlan
}
