// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameRole = "role"

// Role mapped from table <role>
type Role struct {
	ID       int64                 `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`      // id
	Name     string                `gorm:"column:name;type:varchar(16);not null" json:"name"`                   // 角色名称
	IsDelete soft_delete.DeletedAt `gorm:"column:is_delete;type:int unsigned;softDelete:flag" json:"is_delete"` // 是否有效
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
