// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameSchool = "school"

// School mapped from table <school>
type School struct {
	ID       int64                 `gorm:"column:id;type:int(11);primaryKey" json:"id"`                         // id
	Name     string                `gorm:"column:name;type:varchar(32);not null" json:"name"`                   // 名字
	Address  string                `gorm:"column:address;type:varchar(128);not null" json:"address"`            // 地址
	IsDelete soft_delete.DeletedAt `gorm:"column:is_delete;type:int unsigned;softDelete:flag" json:"is_delete"` // 存在标志
}

// TableName School's table name
func (*School) TableName() string {
	return TableNameSchool
}
