// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSelection = "selection"

// Selection mapped from table <selection>
type Selection struct {
	ID                int64 `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`              // id
	StudentID         int64 `gorm:"column:student_id;type:int(11);not null" json:"student_id"`                   // 学生id
	Attribute72       int64 `gorm:"column:Attribute_72;type:int(11);not null" json:"Attribute_72"`               // 第一志愿题目id
	SubjectSecondID   int64 `gorm:"column:subject_second_id;type:int(11);not null" json:"subject_second_id"`     // 第二志愿题目id
	FirstChangeCount  int64 `gorm:"column:first_change_count;type:int(11);not null" json:"first_change_count"`   // 第一志愿修改次数
	SecondChangeCount int64 `gorm:"column:second_change_count;type:int(11);not null" json:"second_change_count"` // 第二志愿修改次数
}

// TableName Selection's table name
func (*Selection) TableName() string {
	return TableNameSelection
}
