// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameStudent = "student"

// Student mapped from table <student>
type Student struct {
	ID        int64                 `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"` // id
	Number    string                `gorm:"column:number;type:varchar(8);not null" json:"number"`           // 学号
	Name      string                `gorm:"column:name;type:varchar(16);not null" json:"name"`
	Password  string                `gorm:"column:password;type:varchar(128);not null" json:"password"`          // 密码
	Grade     int64                 `gorm:"column:grade;type:int(11);not null" json:"grade"`                     // 年级
	Phone     *string               `gorm:"column:phone;type:varchar(11)" json:"phone"`                          // 电话
	Email     *string               `gorm:"column:email;type:varchar(128)" json:"email"`                         // 邮箱
	Gender    int8                  `gorm:"column:gender;type:tinyint(4);not null" json:"gender"`                // 性别
	SubjectID int64                 `gorm:"column:subject_id;type:int(11);not null" json:"subject_id"`           // 题目id
	CollegeID int64                 `gorm:"column:college_id;type:int(11);not null" json:"college_id"`           // 学院
	MajorID   int64                 `gorm:"column:major_id;type:int(11);not null" json:"major_id"`               // 专业
	ClassID   int64                 `gorm:"column:class_id;type:int(11);not null" json:"class_id"`               // 班级
	IsDelete  soft_delete.DeletedAt `gorm:"column:is_delete;type:int unsigned;softDelete:flag" json:"is_delete"` // 存在标志
}

// TableName Student's table name
func (*Student) TableName() string {
	return TableNameStudent
}
