// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameSubjectMajor = "subject_major"

// SubjectMajor mapped from table <subject_major>
type SubjectMajor struct {
	ID        int64                 `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`      // id
	SubjectID int64                 `gorm:"column:subject_id;type:int(11);not null" json:"subject_id"`           // 题目id
	MajorID   int64                 `gorm:"column:major_id;type:int(11);not null" json:"major_id"`               // 专业id
	IsDelete  soft_delete.DeletedAt `gorm:"column:is_delete;type:int unsigned;softDelete:flag" json:"is_delete"` // 存在标志
}

// TableName SubjectMajor's table name
func (*SubjectMajor) TableName() string {
	return TableNameSubjectMajor
}
