// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameTask = "task"

// Task mapped from table <task>
type Task struct {
	ID                 int64                 `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`        // id
	SubjectID          int64                 `gorm:"column:subject_id;type:int(11);not null" json:"subject_id"`             // 题目Id
	According          string                `gorm:"column:according;type:text;not null" json:"according"`                  // 选题依据
	Require            string                `gorm:"column:require;type:text;not null" json:"require"`                      // 论文要求（设计参数）
	Importance         string                `gorm:"column:importance;type:text;not null" json:"importance"`                // 个人工作重点
	Literature         string                `gorm:"column:literature;type:text;not null" json:"literature"`                // 应该阅读的文献
	MajorOpinion       *string               `gorm:"column:major_opinion;type:varchar(128)" json:"major_opinion"`           // 专业审批意见
	MajorApproveTime   *time.Time            `gorm:"column:major_approve_time;type:datetime" json:"major_approve_time"`     // 专业审批时间
	MajorApproveID     *int64                `gorm:"column:major_approve_id;type:int(11)" json:"major_approve_id"`          // 专业审批人
	CollegeOpinoin     *string               `gorm:"column:college_opinoin;type:varchar(128)" json:"college_opinoin"`       // 院校审批意见
	CollegeApproveTime *time.Time            `gorm:"column:college_approve_time;type:datetime" json:"college_approve_time"` // 院校审批时间
	CollegeApproveID   *int64                `gorm:"column:college_approve_id;type:int(11)" json:"college_approve_id"`      // 院校审批人
	BeginTime          time.Time             `gorm:"column:begin_time;type:datetime;not null" json:"begin_time"`            // 工作开始时间
	EndTime            time.Time             `gorm:"column:end_time;type:datetime;not null" json:"end_time"`                // 工作结束时间
	IsDelete           soft_delete.DeletedAt `gorm:"column:is_delete;type:int unsigned;softDelete:flag" json:"is_delete"`   // 存在标志
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
