// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameTeacherTitle = "teacher_title"

// TeacherTitle mapped from table <teacher_title>
type TeacherTitle struct {
	ID       int64                 `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`      // id
	Name     string                `gorm:"column:name;type:varchar(16);not null" json:"name"`                   // 名称
	Level    int8                  `gorm:"column:level;type:tinyint(4);not null" json:"level"`                  // 等级
	IsDelete soft_delete.DeletedAt `gorm:"column:is_delete;type:int unsigned;softDelete:flag" json:"is_delete"` // 存在标志
}

// TableName TeacherTitle's table name
func (*TeacherTitle) TableName() string {
	return TableNameTeacherTitle
}
