// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameTeacher = "teacher"

// Teacher mapped from table <teacher>
type Teacher struct {
	ID        int64                 `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`      // id
	Number    string                `gorm:"column:number;type:varchar(8);not null" json:"number"`                // 工号
	Name      string                `gorm:"column:name;type:varchar(16);not null" json:"name"`                   // 姓名
	Password  string                `gorm:"column:password;type:varchar(128);not null" json:"password"`          // 密码
	RoleID    *int64                `gorm:"column:role_id;type:int(11)" json:"role_id"`                          // 权限
	Phone     *string               `gorm:"column:phone;type:varchar(11)" json:"phone"`                          // 电话
	Email     *string               `gorm:"column:email;type:varchar(64)" json:"email"`                          // 邮箱
	CollegeID int64                 `gorm:"column:college_id;type:int(11);not null" json:"college_id"`           // 学院
	MajorID   int64                 `gorm:"column:major_id;type:int(11);not null" json:"major_id"`               // 专业
	TitleID   int64                 `gorm:"column:title_id;type:int(11);not null" json:"title_id"`               // 职称
	DegreeID  int64                 `gorm:"column:degree_id;type:int(11);not null" json:"degree_id"`             // 学位
	OfficeID  int64                 `gorm:"column:office_id;type:int(11);not null" json:"office_id"`             // 科室
	IsDelete  soft_delete.DeletedAt `gorm:"column:is_delete;type:int unsigned;softDelete:flag" json:"is_delete"` // 存在标志
}

// TableName Teacher's table name
func (*Teacher) TableName() string {
	return TableNameTeacher
}
