// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameTeacherOffice = "teacher_office"

// TeacherOffice mapped from table <teacher_office>
type TeacherOffice struct {
	ID       int64                 `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`      // id
	Name     string                `gorm:"column:name;type:varchar(16);not null" json:"name"`                   // 名称
	IsDelete soft_delete.DeletedAt `gorm:"column:is_delete;type:int unsigned;softDelete:flag" json:"is_delete"` // 存在标志
}

// TableName TeacherOffice's table name
func (*TeacherOffice) TableName() string {
	return TableNameTeacherOffice
}
